/**
 * Pure tokens -> CSS transform. Produces the Tailwind v4 `@theme` block and the
 * `icon-*` utilities from `./tokens`. Has no side effects and no Node imports so
 * it can run in any context (Vite plugin, CLI, tests).
 */
import { tokens } from './tokens';

const HEADER = `/*
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Source of truth: src/shared/design/tokens/tokens.ts
 * Regenerated by the design-tokens Vite plugin and \`bun run tokens:build\`.
 * Edit the .ts source, not this file.
 */`;

function px(value: number): string {
	return `${value}px`;
}

export function tokensToCss(): string {
	const { typography, spacing, radius, elevation, breakpoints, containers, icon } = tokens;

	const lines: string[] = [];
	lines.push('@theme {');

	lines.push('\t/* Typography — size + default weight + line-height per role. */');
	for (const [name, t] of Object.entries(typography)) {
		lines.push(`\t--text-${name}: ${px(t.size)};`);
		lines.push(`\t--text-${name}--line-height: ${t.lineHeight};`);
		lines.push(`\t--text-${name}--font-weight: ${t.weight};`);
	}

	lines.push('');
	lines.push('\t/* Semantic spacing (named layout rhythm) on top of the numeric scale. */');
	for (const [name, value] of Object.entries(spacing)) {
		lines.push(`\t--spacing-${name}: ${px(value)};`);
	}

	lines.push('');
	lines.push('\t/* Border radius. */');
	for (const [name, value] of Object.entries(radius)) {
		lines.push(`\t--radius-${name}: ${px(value)};`);
	}

	lines.push('');
	lines.push('\t/* Elevation. */');
	for (const [name, value] of Object.entries(elevation)) {
		lines.push(`\t--shadow-${name}: ${value};`);
	}

	lines.push('');
	lines.push('\t/* Responsive breakpoints. */');
	for (const [name, value] of Object.entries(breakpoints)) {
		lines.push(`\t--breakpoint-${name}: ${px(value)};`);
	}

	lines.push('');
	lines.push('\t/* Named content-container widths. */');
	for (const [name, value] of Object.entries(containers)) {
		lines.push(`\t--container-${name}: ${px(value)};`);
	}

	lines.push('}');
	lines.push('');

	lines.push('/* Icon size scale — keep icons on these named sizes. */');
	for (const [name, value] of Object.entries(icon)) {
		lines.push(`@utility icon-${name} {`);
		lines.push(`\twidth: ${px(value)};`);
		lines.push(`\theight: ${px(value)};`);
		lines.push('}');
	}

	return `${HEADER}\n\n${lines.join('\n')}\n`;
}
